# Generated by Django 4.1.7 on 2023-02-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('post_uuid', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('access_type', models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC')], max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time')),
                ('likes', models.ManyToManyField(to='blogdata.like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdata.user')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdata.user'),
        ),
    ]
