# Generated by Django 4.1.7 on 2023-02-27 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0002_like_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accesstoken',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
