# Generated by Django 4.1.7 on 2023-03-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0003_user_accesstoken_alter_like_uuid_alter_post_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accesstoken',
        ),
        migrations.AddField(
            model_name='post',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
